# Generated by Django 4.2 on 2022-06-15 23:50

from django.db import migrations, models

from django.contrib.auth.management import create_permissions

def add_permissions(apps, schema_editor):

    for app_config in apps.get_app_configs():
        app_config.models_module = True
        create_permissions(app_config, verbosity=0)
        app_config.models_module = None

def create_groups(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')

    staff, created_staff = Group.objects.get_or_create(name='Staff')
    operator, created_operator = Group.objects.get_or_create(name='Operator')

    if created_operator:
        operator_permission_list = ['Can add late entry', 'Can change late entry', 'Can delete late entry', 'Can view late entry']
        operator_permissions = Permission.objects.filter(name__in=operator_permission_list)   
        operator.permissions.set(operator_permissions)

    if created_staff:
        staff_permission_list = ['Can add batch', 'Can change batch', 'Can delete batch', 'Can view batch', 'Can add branch',\
            'Can change branch', 'Can delete branch', 'Can view branch', 'Can add late entry', 'Can change late entry',\
            'Can delete late entry', 'Can view late entry', 'Can add operator', 'Can change operator', 'Can delete operator',\
            'Can view operator', 'Can add student', 'Can change student', 'Can delete student', 'Can view student', 'Can add venue',\
            'Can change venue', 'Can delete venue', 'Can view venue', 'Can add clipboard', 'Can change clipboard', 'Can delete clipboard',\
            'Can view clipboard', 'Can add clipboard item', 'Can change clipboard item', 'Can delete clipboard item', 'Can view clipboard item',\
            'Can add file', 'Can change file', 'Can delete file', 'Can view file', 'Can add Folder', 'Can use directory listing', 'Can change Folder', 'Can delete Folder', 'Can view Folder']
        staff_permissions = Permission.objects.filter(name__in=staff_permission_list)
        staff.permissions.set(staff_permissions)


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_permissions),
        migrations.RunPython(create_groups)
    ]
