# Generated by Django 4.0.4 on 2022-05-26 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0002_remove_branch_venue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customimage',
            name='branch',
        ),
        migrations.AddField(
            model_name='customimage',
            name='student',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='student_image', to='Core.student'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lateentry',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
